server:
  port: 8088

spring:
  application:
    name: enrollment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/lms_enrollment
    username: postgres
    password: Shareef@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # =========================
  # üî• REDIS CONFIG
  # =========================
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  # =========================
  # üî• KAFKA CONFIG
  # =========================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# =========================
# üî• KAFKA TOPICS
# =========================
topics:
  enrollment: enrollment-events

# =========================
# üîê JWT CONFIG (MUST MATCH AUTH)
# =========================
jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

# =========================
# üìù LOGGING
# =========================
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
