server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Shareef@1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # ================= REDIS =================
  cache:
    type: ${SPRING_CACHE_TYPE:redis}
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  # ================= KAFKA =================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

  # ================= GMAIL (SMTP) =================
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:sk5881998@gmail.com}
    password: ${MAIL_PASSWORD:yztg xbim ggyw qmyj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# ================= JWT =================
jwt:
  secret: ${JWT_SECRET:mysupersecretkeymysupersecretkey}
  expiration: ${JWT_EXPIRATION:3600000}

# ================= GOOGLE OAUTH =================
google:
  client-id: ${GOOGLE_CLIENT_ID:572421778240-akk3kkb4f60ukuv9pcfrpg2ielm09thk.apps.googleusercontent.com}
