server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: postgres
    password: Shareef@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # =========================
  # ğŸ”¥ REDIS CACHE
  # =========================
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  # =========================
  # ğŸ”¥ KAFKA
  # =========================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

# =========================
# ğŸ” JWT (MUST MATCH AUTH SERVICE)
# =========================
jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

# =========================
# ğŸ”¥ TOPICS
# =========================
topics:
  course: course-events
  content: content-events
