server:
  port: 8084

spring:
  application:
    name: video-service

  datasource:
    url: jdbc:postgresql://localhost:5432/videodb
    username: postgres
    password: Shareef@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

  # =========================
  # üî• REDIS
  # =========================
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  # =========================
  # üî• KAFKA
  # =========================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# =========================
# üé• VIDEO CONFIG
# =========================
video:
  upload-dir: videos

# =========================
# üîê JWT (MUST MATCH AUTH)
# =========================
jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

# =========================
# üßµ TOPICS
# =========================
topics:
  video: video-uploaded
