server:
  port: 8087

spring:
  application:
    name: assessment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/assessmentdb
    username: postgres
    password: Shareef@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ğŸ”¥ REDIS
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  # ğŸ”„ KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: assessment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# ğŸ” JWT (MUST MATCH AUTH SERVICE)
jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

# ğŸ§µ TOPICS
topics:
  assessment: assessment-events

# ğŸ“ LOGGING
logging:
  level:
    org.springframework.security: INFO
    org.springframework.kafka: INFO
    com.lms.assessment: DEBUG
