server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/usersdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Shareef@1234}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

  # ================= KAFKA =================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:user-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # ================= REDIS =================
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  # ================= CACHE =================
  cache:
    type: ${SPRING_CACHE_TYPE:redis}

# ================= JWT =================
jwt:
  secret: ${JWT_SECRET:mysupersecretkeymysupersecretkey}
  expiration: ${JWT_EXPIRATION:3600000}

# ================= LOGGING =================
logging:
  level:
    org.springframework.security: ${LOGGING_SECURITY_LEVEL:INFO}
    org.hibernate.SQL: ${LOGGING_HIBERNATE_SQL_LEVEL:DEBUG}

# ================= TOPICS =================
topics:
  user: ${TOPIC_USER:user-events}
