server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: Shareef@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ================= KAFKA =================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # ================= REDIS =================
  data:
    redis:
      host: localhost
      port: 6379

  # ================= CACHE =================
  cache:
    type: redis

# ================= JWT =================
jwt:
  secret: mysupersecretkeymysupersecretkey
  expiration: 3600000

# ================= LOGGING =================
logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

# ================= TOPICS =================
topics:
  user: user-events
